version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: postgres-container
    environment:
      POSTGRES_DB: portfolio_tracker
      POSTGRES_USER: yassine
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
